learning_log/urls.py
'''learning_log의 url 패턴 정의'''

from django.urls import path
from . import views

app_name = 'learning_log'
urlpatterns = [
    # homepage
    path('', views.index, name='index'),
    # Topic list page
    path('topics/', views.topics, name='topics'),
    # Topic detail page
    path('topics/<int:topic_id>', views.topic, name='topic'),
    # add New Topic page
    path('new_topic/', views.new_topic, name='new_topic'),
    # add New Entry page
    path('new_entry/<int:topic_id>/', views.new_entry, name="new_entry"),
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

ll_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_log.urls')),
]

learning_log/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
      '''user가 배우는 주제'''
      text = models.CharField(max_length=200)
      date_added = models.DateTimeField(auto_now_add=True)
      
      def __str__(self):
            '''model의 문자열 표현을 반환'''
            return self.text
      

class Entry(models.Model):
      '''Topic에 대해 배운 내용'''
      topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
      text = models.TextField()
      date_added = models.DateTimeField(auto_now_add=True)
      
      class Meta:
            verbose_name_plural = 'entries'
            
      def __str__(self):
            '''Entry을 나타내는 문자열 반환'''
            if len(self.text) < 50:
                  return f"{self.text}"
            else:
                  return f"{self.text[:50]}..."
      

learning_log/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
      class Meta:
            model = Topic
            fields = ['text']
            labels = {'text': ''}
            
            
class EntryForm(forms.ModelForm):
      class Meta:
            model = Entry
            fields = ['text']
            labels = {'text': ''}
            widgets = {'text': forms.Textarea(attrs={'cols': 80})}
            
            
            

learning_log/views.py
from django.shortcuts import render, redirect

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Create your views here.
def index(requst):
      '''learning log homepage'''
      return render(requst, 
                    'learning_log/index.html')
      
      
def topics(request):
      '''topics list'''
      topics = Topic.objects.order_by('date_added')
      context = {'topics': topics}
      return render(request,
                    'learning_log/topics.html',
                    context)
      
      
def topic(request, topic_id):
      '''topic detail'''
      topic = Topic.objects.get(id=topic_id)
      entries = topic.entry_set.order_by('-date_added')
      context = {'topic': topic, 'entries': entries}
      return render(request, 
                    'learning_log/topic.html',
                    context)
            
      
def new_topic(request):
      '''add new topic'''
      if request.method != 'POST':
            # 빈 폼을 만든다
            form = TopicForm()
      else:
            # POST 데이터를 받았으므로 이를 처리한다
            form = TopicForm(data=request.POST)
            if form.is_valid():
                  form.save()
                  return redirect('learning_log:topics')
      '''
      # 아래의 코드가 실행되는 경우:
      1. GET 요청: 처음 페이지 방문 → 빈 폼 보여줌
      2. POST 요청이지만 데이터가 invalid: 에러 메시지와 함께 폼 다시 보여줌     
      '''
      context = {'form': form}
      return render(request,
                    'learning_log/new_topic.html',
                    context)
      
      
def new_entry(request, topic_id):
      '''특정 topic에 대한 entry 추가하기'''
      topic = Topic.objects.get(id=topic_id)
      
      if request.method != 'POST':
            # POST 메소드가 아닌 경우에는 빈 폼을 만든다
            form = EntryForm()
      else:
            # POST 데이터를 받은 경우 처리하기
            form = EntryForm(data=request.POST)
            if form.is_valid():
                  new_entry = form.save(commit=False)
                  new_entry.topic = topic
                  new_entry.save()
                  return redirect('learning_log:topic', topic_id=topic_id)
      
      # 빈 폼 or invalid 폼을 표시한다
      context = {'topic': topic, 'form': form}
      return render(request,
                    'learning_log/new_entry.html',
                    context)
                  
                  
def edit_entry(request, entry_id):
      '''기존 entry 수정하기'''
      entry = Entry.objects.get(id=entry_id)
      topic = entry.topic          
      
      if request.method != 'POST':
            # 현재 entry로 채워진 폼을 반환
            form = EntryForm(instance=entry)
      else:
            # POST 데이터 받은 것을 처리
            form = EntryForm(instance=entry, data=request.POST)
            if form.is_valid():
                  form.save()
                  return redirect('learning_log:topic', topic_id=topic.id)
            
      context = {'entry': entry, 'topic':topic, 'form': form}
      return render(request, 'learning_log/edit_entry.html', context)


                    

learning_log/templates/learning_log/base.html
<p>
      <a href="{% url 'learning_log:index' %}">Learning Log</a> -
      <a href="{% url 'learning_log:topics' %}">Topics</a>
</p>

{% block content %}{% endblock content %}

learning_log/templates/learning_log/edit_entry.html
{% extends "learning_log/base.html" %}

{% block content %}

<p><a href="{% url 'learning_log:topic' topic.id %}">{{ topic }}</a></p>

<p>Edit entry:</p>

<form action="{% url "learning_log:edit_entry" entry.id %}" method='post'>
      {% csrf_token %}
      {{ form.as_div }}
      <button name="submit">Save Changes</button>
</form>



{% endblock content %}

learning_log/templates/learning_log/index.html
{% extends "learning_log/base.html" %}

{% block content %}
<p>Learning Log helps you keep track of your learning, fro any topic you're interested in.</p>
{% endblock content %}

learning_log/templates/learning_log/new_entry.html
{% extends "learning_log/base.html" %}

{% block content %}
<p>
      <a href="{% url 'learning_log:topic' topic.id %}">{{ topic }}</a>
</p>

<p>Add a new entry:</p>
<form action="{% url 'learning_log:new_entry' topic.id %}" method='post'>
      {% csrf_token %}
      {{ form.as_div }}
      <button name='submit'>Add entry</button>
</form>


{% endblock content %}

learning_log/templates/learning_log/new_topic.html
{% extends "learning_log/base.html" %}

{% block content %}
<p>Add a new topic:</p>

<form action="{% url 'learning_log:new_topic' %}" method='post'>
      {% csrf_token %}
      {{ form.as_div }}
      <button name="submit">Add topic</button>
</form>

{% endblock content %}

learning_log/templates/learning_log/topic.html
{% extends 'learning_log/base.html' %}

{% block content %}

<p>Topic: {{ topic }}</p>

<p>Entries:</p>
<p>
      <a href="{% url 'learning_log:new_entry' topic.id %}">Add new entry</a>
</p>      


<ul>
      {% for entry in entries %}
            <li>
                  <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
                  <p>{{ entry.text|linebreaks }}</p>
                  <p>
                        <a href="{% url 'learning_log:edit_entry' entry.id %}">
                              Edit entry
                        </a>
                  </p>
            </li>
      {% empty %}
            <li>There are no entries for this topic yet.</li>
      {% endfor %}
</ul>


{% endblock content %}

learning_log/templates/learning_log/topics.html
{% extends 'learning_log/base.html' %}

{% block content %}

<p>Topics</p>
<ul>
      {% for topic in topics %}
            <li>
                  <a href="{% url 'learning_log:topic' topic.id %}">
                  {{ topic.text }}</a>
            </li>
      {% empty %}
            <li>No topics have been added yet.</li>
      {% endfor %}
</ul>

<a href="{% url 'learning_log:new_topic' %}">Add a new topic</a>

{% endblock content %}